title: ACM@UC
description: ACM student chapter at the University of Cincinnati.
url: "https://acmatuc.org"
ga: UA-38523596-2

social:
  github: ACMatUC
  twitter: ACMatUCorg
  email: acmatuc@gmail.com

markdown: kramdown
theme: minima

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
